### ISSUE TITLE
url unreachable

### ISSUE THREAD

**Issue by ramap87** [Accenture/adop-jenkins-slave#3]
hi team , the below url is unreachable , please can you update the dockerfile 
http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
thanks

**Comment by anton-kasperovich** [comment]
I can confirm, url is unreachable and docker build is broken, it's stuck on:

```
Step 15 : RUN rpm -ivh http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm && yum --enablerepo=rpmforge-extras install -y git
 ---> Running in 346088b62fbd
curl: (7) Failed connect to pkgs.repoforge.org:80; Connection refused
error: skipping http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm - transfer failed
Retrieving http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
The command '/bin/sh -c rpm -ivh http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm && yum --enablerepo=rpmforge-extras install -y git' returned a non-zero code: 1
```

https://wiki.centos.org/AdditionalResources/Repositories/RPMForge

```
RPMForge/RepoForge is a dead project. It is not maintained. DO NOT USE.
```

I also want to improve using specific version of libraries and tools like Docker or AWS CLI, which for now just download every build latest versions which could break image.

Work in progress by me.

**Comment by zrks** [comment]
is there specific reason why there is included this rpm? Why not default one?
