### ISSUE TITLE
some mis-spellings and grammar errors on the readme

### ISSUE THREAD

**Issue by teamschwarz** [Accenture/adop-jenkins-slave#4]
how can i help fix them?

**Comment by anton-kasperovich** [comment]
Hi @teamschwarz , you could find more information about how-to make a fork and create a pull request on Github Help pages like this one: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Steps would be like:
1. Make a fork of this repository, you could find this "Fork" button in header of any git repository on the Github, https://github.com/Accenture/adop-jenkins-slave (as a result you should have the same adop-jenkins-slave git repository under your personal github account)
2. Make a desirable changes via git commit in your own forked git repository (which you already forked on this stage as a first step) or via online editor, i assume as you want to change just README file, you could make it quickly via online editor, you could find more information here https://help.github.com/articles/editing-files-in-your-repository/
3. When you made a change and pushed it to forked repository, there is two options how you can create a Pull Request:
3.1 Check main page of your forked repository, there should be notice with big green button to create Pull Request to main repository.
3.2. Open new Pull Request via "New pull request" button from this page https://github.com/Accenture/adop-jenkins-slave/pulls

Looking forward to see your pull requests, thank you!

**Comment by anton-kasperovich** [comment]
Closing this one, as answer was provided and there's no activities for the long time. Thank you for the question.
